### ISSUE TITLE
never rescue Exception without re-raising

### ISSUE THREAD

**Issue by SampsonCrowley** [bwillis/versioncake#105]
it's bad style to use the absolute base `Exception` class.

Why is `Exception` thrown and caught in multiple places instead of `StandardError` or even `ArgumentError` or at least a new custom subclass of Exception so you dont accidentally catch *all* Exceptions

It's fine to throw Exception if it's something that shouldn't be caught, but then you're also catching Exception in VersionedRequest

Here are just a few examples: 
[Thrown in ExtractionStrategy#L15](https://github.com/bwillis/versioncake/blob/9cd984272f108915d738df17f0a1bf0dd22450d8/lib/versioncake/strategies/extraction_strategy.rb#L15)

[Thrown in ExtractionStrategy#L31](https://github.com/bwillis/versioncake/blob/3b3de388b842ca7b572afd0caef50efee8f0a3c6/lib/versioncake/strategies/extraction_strategy.rb#L31)

[Caught in VersionedRequest#L18](https://github.com/bwillis/versioncake/blob/3b3de388b842ca7b572afd0caef50efee8f0a3c6/lib/versioncake/versioned_request.rb#L18)

**Comment by SampsonCrowley** [comment]
@bwillis is this by a purposeful design?

**Comment by bwillis** [comment]
Ah yeah, probably just laziness from time of writing. PRs are welcome 😄
