### ISSUE TITLE
Define returned errors

### ISSUE THREAD

**Issue by espen** [bwillis/versioncake#38]
I couldn't see find any details about how to return errors.

Currently my API does not return errors in a very sensible way. I would like keep this in version1 and introduce a version2 which improves the way errors are returned in the API.

**Comment by bwillis** [comment]
Hey Espen, 

Thanks for the question. I had a similar issue and can explain how I resolved it, though definitely not the only way. Let me know if you have any questions!

## 1. Identify errors
The first thing I did was to identify which errors that I wanted to handle and how they are occurring. Pretty commonly they are exceptions and model errors.

## 2. Map errors to payloads 
Understand what the current error payloads are and start creating views (if not existing already) for the current version:

shared/error_message.json.v1.jbuilder:
```
# ActiveRecord::RecordNotFound has no payload
```
shared/error_model.json.v1.jbuilder
```ruby
json.messages @model.full_messages
```

## 3. Capture Exceptions
Exceptions are handled mostly by Rails, so handling them in application code is an important step to start customizing them:
```ruby
rescue_from ActiveRecord::RecordNotFound, :versioned_errors
rescue_from UnsupportedVersionError, :versioned_errors
#rescue_from Other::Errors, :versioned_errors

def versioned_errors(exception)
  render 'shared/error_message', message: exception.message
end
```

## 4. Handle model errors
For model error checks we can call our shared errors template that will work for v1.
```ruby
def create
  @model = model.save
  if model.errors?
    render 'shared/error_model'
  else
    render 'model/show'
  end
end
```

## 5. Exceptions in your exceptions
On occasion I had errors that did not match the existing v1 format. These had to be handled in one off cases. For example:
```ruby
def create
  @model = model.save
  if model.errors?
    if requested_version < 2
       render json: { data: { errors: 'This is a different error message format.' } }
    else
      render 'shared/error_model'
    end
  else
    render 'model/show'
  end
end
```
## 6. Add tests
Add any missing tests to avoid breaking v1.

## 7. Add version 2
```
# shared/error_message.json.v2.jbuilder
json.message message
```
```
# shared/error_model.json.v2.jbuilder
json.messages @model.messages
```

**Comment by espen** [comment]
Wow, that's a great and detailed answer. Put it up on the wiki!

👍👍

Versioncake looks great. Adding version 2 in our api is still on the roadmap but thanks for the info and I'll definitively look further into this when the time comes for it.

**Comment by bwillis** [comment]
Thanks, I'll be sure to add the documentation. Good luck!
