### ISSUE TITLE
Feature Request: Include version in Content-Type

### ISSUE THREAD

**Issue by dkubb** [bwillis/versioncake#39]
When using HTTP Accept header negotiation would it be possible to have versioncake set the negotiated version in the returned `Content-Type` header?

So for example if I do:

```shell
http http://localhost:3000/ 'Accept:application/vnd.api+json;version=1'
```

I should receive something like:

```http
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json; charset=utf-8; version=1
...
```

**Comment by bwillis** [comment]
Thanks for the request!

I do think that this is a pretty nice feature to have. Is this something you'd be interested in making a PR for?
