### ISSUE TITLE
Next Gem Release?

### ISSUE THREAD

**Issue by kjanoudi** [bwillis/versioncake#57]
When will you be publishing an update to the gem that's up right now with the latest changes in the repo?

**Comment by krzysiek1507** [comment]
@bwillis is the v3.2 released? I can't see it in rubygems. Thanks!

**Comment by bwillis** [comment]
Sorry all! I am a little behind on releasing the latest gem, I'll schedule some time tonight to do it. Thanks for your patience! 🌈

**Comment by bwillis** [comment]
I published the latest version v3.2, please let me know if you have an issues. Thanks!
