### ISSUE TITLE
Deprecated versions response

### ISSUE THREAD

**Issue by vanessanutrio** [bwillis/versioncake#59]
What is the main difference between responses of supported and deprecated versions? I understand deprecated versions are still supported but I assume I would find a warning somewhere.

**Comment by bwillis** [comment]
Hey @vanessanutrio,

Thanks for the question. There is a helper in the controller available `is_deprecated_version?` that can help you craft a response which would contain a warning, but there's no automatic warning built in. 

Do you think this would be useful and how do you think it would work?

Thanks!

**Comment by vanessanutrio** [comment]
Thanks @bwillis, I think the helper is useful for my case.

**Comment by bwillis** [comment]
Ok! Let me know if there's anything we could add to VersionCake to help out 🌈
