### ISSUE TITLE
Documentation on supported_version_numbers

### ISSUE THREAD

**Issue by hlascelles** [bwillis/versioncake#70]
Setting up config for a v3 application, we came across this:

```
VersionCake.setup do |config|
  config.resources do |r|
    r.resource %r{/users}, [], [1], [4]
    r.resource %r{.*}, [], [], [2, 3]
  end
end

VersionCake.config.supported_version_numbers #=> [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```

I can see from the [versioncake source](https://github.com/bwillis/versioncake/blob/master/lib/versioncake/configuration.rb#L7) that the long list is the "default" set. 

Why is it there? Isn't the list of `supported_version_numbers` just a union of all the resource `supported_versions` (deprecated + supported), ie [1, 2, 3, 4]?

**Comment by bwillis** [comment]
That was the default set to ensure gem onboarding was easier for v2. In v3, you are correct, [it's deprecated](https://github.com/bwillis/versioncake#configuration-changes-1) and the supported versions are gleaned from the resources.

Does that make sense?

**Comment by hlascelles** [comment]
OK great :+1:. I guess I was expecting them to be "completely gone". Maybe have a verbose `puts` line stating that?

**Comment by bwillis** [comment]
TBH I'm not sure why it isn't removed, I'll have to look into it - a bit of technical debt 😄
