### ISSUE TITLE
v4 update for rails 6 support has dependency conflict

### ISSUE THREAD

**Issue by trak3r** [bwillis/versioncake#87]
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (~> 6.0) was resolved to 6.0.2.1, which depends on
      actionpack (= 6.0.2.1)

    versioncake (>= 4.0) was resolved to 4.0.0, which depends on
      actionpack (~> 5.0)
```

**Comment by bwillis** [comment]
Thanks for filing! Looks like I messed up the gemspec file, any chance you could do a quick check agains #89?

**Comment by bwillis** [comment]
I tested this locally and verified the fix works, lemme know if it doesn't work for you.

**Comment by trak3r** [comment]
thanks. sorry i didn't have time to test your fix yesterday and might not for another day or two.

**Comment by trak3r** [comment]
yup i managed to get a few free minutes and bundle update and it's all good now. thanks!

**Comment by bwillis** [comment]
No worries, thanks for confirming!
