### ISSUE TITLE
VersionChecker initialize bug?

### ISSUE THREAD

**Issue by owen-c** [bwillis/versioncake#97]
Am I crazy or is this code wrong because of the order?

```ruby
def initialize(version, resource)
  @version, @resource = resource, version
end
```

**Comment by owen-c** [comment]
Ah possibly  not a bug because its called like so. Just really confusing :P

```ruby
def check_version(resource, version)
  VersionCake::VersionChecker.new(resource, version).execute
end
```

**Comment by bwillis** [comment]
Oh wow, nice find! We should fix that for sure, feel free to open a PR or I'll get to it in a few days or so 🤞

**Comment by owen-c** [comment]
Fixed
